project:
  type: website

website:
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects 

  page-footer: 
    right: "&copy; 2025, Sophia Yi"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    published-title: "last updated"
    reference-location: document
    code-fold: false
    code-summary: ""
    fontsize: 1.3em


execute: 
  freeze: auto
